-- TTRC Store: Initial Database Schema
-- Migration: 20260920000001_initial_schema.sql
-- All monetary values stored as INTEGER (paise). 1 INR = 100 paise.
-- All primary keys are UUIDs generated by gen_random_uuid().

-- ─── Extensions ──────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";  -- for typo-tolerant text search
CREATE EXTENSION IF NOT EXISTS "unaccent"; -- for accent-insensitive search

-- ─── Profiles ────────────────────────────────────────────────────────────────
CREATE TABLE profiles (
  id          UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name   TEXT,
  phone       TEXT,
  avatar_url  TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── User Roles ───────────────────────────────────────────────────────────────
-- Roles are NEVER stored in auth.users.raw_user_meta_data.
-- They live in a separate table to prevent client-side role escalation.
CREATE TYPE user_role AS ENUM ('customer', 'admin', 'staff');

CREATE TABLE user_roles (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role       user_role NOT NULL DEFAULT 'customer',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id)
);

-- ─── Categories ───────────────────────────────────────────────────────────────
CREATE TABLE categories (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT NOT NULL,
  slug        TEXT NOT NULL UNIQUE,
  parent_id   UUID REFERENCES categories(id) ON DELETE SET NULL,
  icon        TEXT,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  seo_title   TEXT,
  seo_desc    TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_categories_slug ON categories(slug);
CREATE INDEX idx_categories_parent ON categories(parent_id);

-- ─── Products ─────────────────────────────────────────────────────────────────
CREATE TYPE product_type   AS ENUM ('kit', 'spare_part', 'general');
CREATE TYPE product_status AS ENUM ('draft', 'published', 'archived');

CREATE TABLE products (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name                 TEXT NOT NULL,
  slug                 TEXT NOT NULL UNIQUE,
  sku                  TEXT NOT NULL UNIQUE,
  type                 product_type NOT NULL DEFAULT 'general',
  brand                TEXT,
  category_id          UUID NOT NULL REFERENCES categories(id),
  short_description    TEXT NOT NULL DEFAULT '',
  long_description     TEXT,
  -- Pricing (INTEGER paise — NEVER FLOAT)
  price_paise          INTEGER NOT NULL CHECK (price_paise > 0),
  mrp_paise            INTEGER CHECK (mrp_paise > 0),
  -- GST
  gst_percent          SMALLINT NOT NULL DEFAULT 18 CHECK (gst_percent IN (0, 5, 12, 18, 28)),
  hsn_code             TEXT,
  -- Inventory
  stock_qty            INTEGER NOT NULL DEFAULT 0 CHECK (stock_qty >= 0),
  low_stock_threshold  INTEGER NOT NULL DEFAULT 5,
  -- Physical
  weight_grams         INTEGER CHECK (weight_grams > 0),
  length_mm            INTEGER CHECK (length_mm > 0),
  width_mm             INTEGER CHECK (width_mm > 0),
  height_mm            INTEGER CHECK (height_mm > 0),
  -- Metadata
  tags                 TEXT[] NOT NULL DEFAULT '{}',
  status               product_status NOT NULL DEFAULT 'draft',
  -- SEO
  seo_title            TEXT,
  seo_description      TEXT,
  seo_keywords         TEXT[] NOT NULL DEFAULT '{}',
  -- Full-text search vector (updated by trigger)
  search_vector        TSVECTOR,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_products_slug        ON products(slug);
CREATE INDEX idx_products_sku         ON products(sku);
CREATE INDEX idx_products_category    ON products(category_id);
CREATE INDEX idx_products_status      ON products(status);
CREATE INDEX idx_products_type        ON products(type);
CREATE INDEX idx_products_price       ON products(price_paise);
CREATE INDEX idx_products_search      ON products USING GIN(search_vector);
CREATE INDEX idx_products_tags        ON products USING GIN(tags);

-- Full-text search update trigger
CREATE OR REPLACE FUNCTION update_product_search_vector()
RETURNS TRIGGER AS $$
BEGIN
  NEW.search_vector :=
    setweight(to_tsvector('english', coalesce(NEW.name, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(NEW.brand, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(NEW.short_description, '')), 'C') ||
    setweight(to_tsvector('english', coalesce(array_to_string(NEW.tags, ' '), '')), 'C');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER products_search_vector_update
  BEFORE INSERT OR UPDATE ON products
  FOR EACH ROW EXECUTE FUNCTION update_product_search_vector();

-- ─── Product Images ───────────────────────────────────────────────────────────
CREATE TABLE product_images (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id  UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  url         TEXT NOT NULL,
  alt         TEXT NOT NULL DEFAULT '',
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_product_images_product ON product_images(product_id, sort_order);

-- ─── Product Specs ────────────────────────────────────────────────────────────
CREATE TABLE product_specs (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id  UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  key         TEXT NOT NULL,
  value       TEXT NOT NULL,
  sort_order  INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_product_specs_product ON product_specs(product_id);

-- ─── Product Variants ─────────────────────────────────────────────────────────
CREATE TABLE product_variants (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id   UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  name         TEXT NOT NULL,
  sku          TEXT NOT NULL UNIQUE,
  price_paise  INTEGER NOT NULL CHECK (price_paise > 0),
  mrp_paise    INTEGER CHECK (mrp_paise > 0),
  stock_qty    INTEGER NOT NULL DEFAULT 0 CHECK (stock_qty >= 0),
  images       JSONB NOT NULL DEFAULT '[]',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_variants_product ON product_variants(product_id);

-- ─── Product Compatibility (Kit ↔ Spare Parts) ───────────────────────────────
-- Many-to-many between kits and spare parts.
CREATE TABLE product_compatibility (
  kit_id    UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  spare_id  UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  PRIMARY KEY (kit_id, spare_id),
  CHECK (kit_id != spare_id)
);

CREATE INDEX idx_compat_spare ON product_compatibility(spare_id);

-- ─── Addresses ────────────────────────────────────────────────────────────────
CREATE TABLE addresses (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  label       TEXT,
  full_name   TEXT NOT NULL,
  phone       TEXT NOT NULL,
  line1       TEXT NOT NULL,
  line2       TEXT,
  city        TEXT NOT NULL,
  state       TEXT NOT NULL,
  pincode     TEXT NOT NULL CHECK (pincode ~ '^\d{6}$'),
  is_default  BOOLEAN NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_addresses_user ON addresses(user_id);

-- ─── Carts ────────────────────────────────────────────────────────────────────
CREATE TABLE carts (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  session_id  TEXT,
  coupon_code TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (user_id IS NOT NULL OR session_id IS NOT NULL)
);

CREATE INDEX idx_carts_user    ON carts(user_id);
CREATE INDEX idx_carts_session ON carts(session_id);

CREATE TABLE cart_items (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cart_id               UUID NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
  product_id            UUID NOT NULL REFERENCES products(id),
  variant_id            UUID REFERENCES product_variants(id),
  quantity              INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0 AND quantity <= 99),
  -- Snapshots at time of add (for display only — server re-validates at checkout)
  snapshot_name         TEXT NOT NULL,
  snapshot_price_paise  INTEGER NOT NULL CHECK (snapshot_price_paise > 0),
  snapshot_image_url    TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(cart_id, product_id, variant_id)
);

CREATE INDEX idx_cart_items_cart ON cart_items(cart_id);

-- ─── Wishlists ────────────────────────────────────────────────────────────────
CREATE TABLE wishlists (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id  UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, product_id)
);

CREATE INDEX idx_wishlists_user ON wishlists(user_id);

-- ─── Orders ───────────────────────────────────────────────────────────────────
CREATE TYPE order_status AS ENUM (
  'pending_payment', 'payment_failed', 'confirmed', 'processing',
  'packed', 'shipped', 'out_for_delivery', 'delivered',
  'cancelled', 'return_requested', 'returned', 'refunded'
);

CREATE TYPE payment_method AS ENUM ('razorpay', 'cod');

CREATE TABLE orders (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  status                 order_status NOT NULL DEFAULT 'pending_payment',
  shipping_address_id    UUID REFERENCES addresses(id),
  -- Snapshot of shipping address (in case address is deleted)
  shipping_address_snap  JSONB,
  -- Totals (paise) — ALL computed server-side, never trust client
  subtotal_paise         INTEGER NOT NULL CHECK (subtotal_paise >= 0),
  shipping_paise         INTEGER NOT NULL DEFAULT 0 CHECK (shipping_paise >= 0),
  discount_paise         INTEGER NOT NULL DEFAULT 0 CHECK (discount_paise >= 0),
  -- GST breakdown
  taxable_paise          INTEGER NOT NULL DEFAULT 0,
  cgst_paise             INTEGER NOT NULL DEFAULT 0,
  sgst_paise             INTEGER NOT NULL DEFAULT 0,
  igst_paise             INTEGER NOT NULL DEFAULT 0,
  total_gst_paise        INTEGER NOT NULL DEFAULT 0,
  total_paise            INTEGER NOT NULL CHECK (total_paise >= 0),
  -- Coupon
  coupon_code            TEXT,
  coupon_discount_paise  INTEGER NOT NULL DEFAULT 0,
  -- Payment
  payment_method         payment_method NOT NULL,
  razorpay_order_id      TEXT UNIQUE,
  razorpay_payment_id    TEXT UNIQUE,
  -- Invoice
  invoice_number         TEXT UNIQUE,
  invoice_url            TEXT,
  -- Notes
  customer_note          TEXT,
  admin_note             TEXT,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_orders_user       ON orders(user_id);
CREATE INDEX idx_orders_status     ON orders(status);
CREATE INDEX idx_orders_created    ON orders(created_at DESC);
CREATE INDEX idx_orders_razorpay   ON orders(razorpay_order_id);
CREATE INDEX idx_orders_invoice    ON orders(invoice_number);

CREATE TABLE order_items (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id            UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id          UUID REFERENCES products(id) ON DELETE SET NULL,
  variant_id          UUID REFERENCES product_variants(id) ON DELETE SET NULL,
  quantity            INTEGER NOT NULL CHECK (quantity > 0),
  unit_price_paise    INTEGER NOT NULL CHECK (unit_price_paise > 0),
  gst_percent         SMALLINT NOT NULL DEFAULT 18,
  hsn_code            TEXT,
  snapshot_name       TEXT NOT NULL,
  snapshot_sku        TEXT NOT NULL,
  snapshot_image_url  TEXT
);

CREATE INDEX idx_order_items_order   ON order_items(order_id);
CREATE INDEX idx_order_items_product ON order_items(product_id);

-- ─── Payments ─────────────────────────────────────────────────────────────────
CREATE TYPE payment_status AS ENUM ('pending', 'captured', 'failed', 'refunded', 'partially_refunded');

CREATE TABLE payments (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id              UUID NOT NULL REFERENCES orders(id),
  razorpay_payment_id   TEXT UNIQUE,
  razorpay_order_id     TEXT,
  razorpay_signature    TEXT,
  amount_paise          INTEGER NOT NULL,
  status                payment_status NOT NULL DEFAULT 'pending',
  method                TEXT,
  webhook_event_id      TEXT UNIQUE, -- for idempotency
  raw_payload           JSONB,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_payments_order    ON payments(order_id);
CREATE INDEX idx_payments_razorpay ON payments(razorpay_payment_id);

-- ─── Shipments ────────────────────────────────────────────────────────────────
CREATE TABLE shipments (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id              UUID NOT NULL REFERENCES orders(id),
  provider              TEXT NOT NULL DEFAULT 'manual', -- 'shiprocket' | 'delhivery' | 'manual'
  tracking_number       TEXT,
  tracking_url          TEXT,
  label_url             TEXT,
  provider_shipment_id  TEXT,
  estimated_delivery    DATE,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_shipments_order ON shipments(order_id);

-- ─── Reviews ──────────────────────────────────────────────────────────────────
CREATE TABLE reviews (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id       UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  user_id          UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  order_id         UUID REFERENCES orders(id),
  rating           SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  title            TEXT,
  body             TEXT,
  is_verified      BOOLEAN NOT NULL DEFAULT FALSE, -- verified purchase
  is_approved      BOOLEAN NOT NULL DEFAULT FALSE, -- moderated
  helpful_count    INTEGER NOT NULL DEFAULT 0,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(product_id, user_id) -- one review per product per user
);

CREATE INDEX idx_reviews_product ON reviews(product_id, is_approved);
CREATE INDEX idx_reviews_user    ON reviews(user_id);

CREATE TABLE review_media (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  review_id  UUID NOT NULL REFERENCES reviews(id) ON DELETE CASCADE,
  url        TEXT NOT NULL,
  type       TEXT NOT NULL DEFAULT 'image'
);

CREATE TABLE review_votes (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  review_id  UUID NOT NULL REFERENCES reviews(id) ON DELETE CASCADE,
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  is_helpful BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(review_id, user_id)
);

-- ─── Coupons ──────────────────────────────────────────────────────────────────
CREATE TYPE coupon_type AS ENUM ('percent', 'flat');

CREATE TABLE coupons (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code                TEXT NOT NULL UNIQUE,
  type                coupon_type NOT NULL,
  value               INTEGER NOT NULL CHECK (value > 0), -- percent (1-100) or paise
  min_order_paise     INTEGER NOT NULL DEFAULT 0,
  max_uses            INTEGER,          -- NULL = unlimited
  uses_per_user       INTEGER,          -- NULL = unlimited
  current_uses        INTEGER NOT NULL DEFAULT 0,
  expires_at          TIMESTAMPTZ,
  is_active           BOOLEAN NOT NULL DEFAULT TRUE,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_coupons_code ON coupons(code);

CREATE TABLE coupon_redemptions (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  coupon_id   UUID NOT NULL REFERENCES coupons(id),
  user_id     UUID NOT NULL REFERENCES auth.users(id),
  order_id    UUID NOT NULL REFERENCES orders(id),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── Banners ──────────────────────────────────────────────────────────────────
CREATE TABLE banners (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title       TEXT NOT NULL,
  image_url   TEXT NOT NULL,
  link_url    TEXT,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  starts_at   TIMESTAMPTZ,
  ends_at     TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── Inventory Movements (Audit Trail) ───────────────────────────────────────
CREATE TYPE inventory_reason AS ENUM (
  'sale', 'return', 'adjustment', 'restock', 'damage', 'import'
);

CREATE TABLE inventory_movements (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id  UUID NOT NULL REFERENCES products(id),
  variant_id  UUID REFERENCES product_variants(id),
  delta       INTEGER NOT NULL,  -- positive = in, negative = out
  reason      inventory_reason NOT NULL,
  reference   TEXT,              -- order_id, adjustment note, etc.
  user_id     UUID REFERENCES auth.users(id),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_inventory_product ON inventory_movements(product_id, created_at DESC);

-- ─── Audit Logs ───────────────────────────────────────────────────────────────
CREATE TABLE audit_logs (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID REFERENCES auth.users(id),
  action       TEXT NOT NULL,
  table_name   TEXT NOT NULL,
  record_id    TEXT,
  old_data     JSONB,
  new_data     JSONB,
  ip_address   INET,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_audit_user   ON audit_logs(user_id, created_at DESC);
CREATE INDEX idx_audit_table  ON audit_logs(table_name, record_id);

-- ─── Settings ─────────────────────────────────────────────────────────────────
CREATE TABLE settings (
  key        TEXT PRIMARY KEY,
  value      JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by UUID REFERENCES auth.users(id)
);

-- Initial settings
INSERT INTO settings (key, value) VALUES
  ('shipping_free_threshold_paise', '99900'),
  ('cod_max_order_paise', '500000'),
  ('cod_enabled', 'true'),
  ('gstin', '"PLACEHOLDER_GSTIN"'),
  ('business_state', '"Tamil Nadu"'),
  ('business_state_code', '"33"');

-- ─── Newsletter Subscribers ───────────────────────────────────────────────────
CREATE TABLE newsletter_subscribers (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email       TEXT NOT NULL UNIQUE,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── Device Tokens (Push Notifications — Phase 8) ────────────────────────────
CREATE TABLE device_tokens (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  token       TEXT NOT NULL UNIQUE,
  platform    TEXT NOT NULL, -- 'ios' | 'android'
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_device_tokens_user ON device_tokens(user_id);

-- ─── Updated_at Trigger Function ─────────────────────────────────────────────
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply to all tables with updated_at
CREATE TRIGGER set_updated_at BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON categories FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON addresses FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON carts FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON cart_items FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON shipments FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON reviews FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON device_tokens FOR EACH ROW EXECUTE FUNCTION set_updated_at();
